services:
  - type: web
    name: crypto-miner-bot-web
    env: python
    runtime: docker
    rootDir: .
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: TELEGRAM_TOKEN
        sync: true
